version: "3.8"

services:
  app:
    build: .
    ports:
      - "3001:3000"
    environment:
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
      NEXT_PUBLIC_CLERK_SIGN_IN_URL: ${NEXT_PUBLIC_CLERK_SIGN_IN_URL}
      NEXT_PUBLIC_CLERK_SIGN_UP_URL: ${NEXT_PUBLIC_CLERK_SIGN_UP_URL}
      NEXT_PUBLIC_GEMNI_API_KEY: ${NEXT_PUBLIC_GEMNI_API_KEY}
      NEXT_PUBLIC_DB_CONNECTION_STRING: ${NEXT_PUBLIC_DB_CONNECTION_STRING}
      NEXT_PUBLIC_FIREBASE_API_KEY: ${NEXT_PUBLIC_FIREBASE_API_KEY}
      NEXT_PUBLIC_HOST_NAME: ${NEXT_PUBLIC_HOST_NAME}
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: course-generator
      POSTGRES_USER: neondb_owner
      POSTGRES_PASSWORD: UfiBlEI8m9Kj
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
